server:
  port: 80

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/userServiceFallback
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
                name: contact-service
                fallbackuri: forward:/contactServiceFallback

hytrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
          timeoutInMilliseconds: 2000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/